-- MySQL Workbench Forward Engineering
-- Base de datos de prueba

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgc_beta` DEFAULT CHARACTER SET utf8 ;
USE `sgc_beta`;

-- -----------------------------------------------------
-- Table `sgc`.`SGC_PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc_beta`.`SGC_PERFIL` (
  `PERF_NUMERO` INT NOT NULL,
  `SGC_PLAYA_PLA_ID` INT NOT NULL,
  PRIMARY KEY (`PERF_NUMERO`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sgc`.`SGC_BITACORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc_beta`.`SGC_BITACORA` (
  `BIT_ID` INT NOT NULL AUTO_INCREMENT,
  `BIT_FECHA_HORA` DATETIME NULL,
  `SGC_PERFIL_PERF_NUMERO` INT NOT NULL,
  PRIMARY KEY (`BIT_ID`),
  INDEX `fk_SGC_BITACORA_SGC_PERFIL1_idx` (`SGC_PERFIL_PERF_NUMERO` ASC),
  CONSTRAINT `fk_SGC_BITACORA_SGC_PERFIL1`
    FOREIGN KEY (`SGC_PERFIL_PERF_NUMERO`)
    REFERENCES `sgc_beta`.`SGC_PERFIL` (`PERF_NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sgc`.`SGC_MEDICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc_beta`.`SGC_MEDICION` (
  `MED_ID` INT NOT NULL AUTO_INCREMENT,
  `MED_ESTACION` INT NOT NULL,
  `MED_ESTACION_MEDICION` VARCHAR(45) NOT NULL,
  `MED_DISTANCIA_HORIZONTAL` DECIMAL(4,2) NOT NULL,
  `MED_DISTANCIA_VERTICAL` DECIMAL(4,2) NOT NULL,
  `SGC_BITACORA_BIT_ID` INT NOT NULL,
  PRIMARY KEY (`MED_ID`),
  INDEX `fk_SGC_MEDICION_SGC_BITACORA1_idx` (`SGC_BITACORA_BIT_ID` ASC),
  CONSTRAINT `fk_SGC_MEDICION_SGC_BITACORA1`
    FOREIGN KEY (`SGC_BITACORA_BIT_ID`)
    REFERENCES `sgc_beta`.`SGC_BITACORA` (`BIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO SGC_PERFIL
	(PERF_NUMERO, SGC_PLAYA_PLA_ID)
VALUES
	(1, 1)
;

INSERT INTO
	SGC_BITACORA (BIT_FECHA_HORA, SGC_PERFIL_PERF_NUMERO)
VALUES
	('2016-12-24', 1),
	('2016-12-25', 1),
	('2016-12-26', 1)
;

INSERT INTO
	SGC_MEDICION (MED_ESTACION, MED_ESTACION_MEDICION, MED_DISTANCIA_HORIZONTAL, MED_DISTANCIA_VERTICAL, SGC_BITACORA_BIT_ID)
VALUES
	(0, 0, 0, 0, 1),
	(0, 1, 0.0, 213/100, 1),
	(1, 2, 1.5, 30/100, 1),
	(2, 3, 1.5, 36/100, 1),
	(3, 4, 1.5, 50/100, 1),
	(4, 5, 1.5, 61/100, 1),
	(5, 6, 1.5, 76/100, 1)
;

INSERT INTO
	SGC_MEDICION (MED_ESTACION, MED_ESTACION_MEDICION, MED_DISTANCIA_HORIZONTAL, MED_DISTANCIA_VERTICAL, SGC_BITACORA_BIT_ID)
VALUES
	(0, 0, 0, 0, 2),
	(0, 1, 0.0, 213/100, 2),
	(1, 2, 1.5, 34/100, 2),
	(2, 3, 1.5, 36/100, 2),
	(3, 4, 1.5, 23/100, 2),
	(4, 5, 1.5, 11/100, 2),
;

INSERT INTO
	SGC_MEDICION (MED_ESTACION, MED_ESTACION_MEDICION, MED_DISTANCIA_HORIZONTAL, MED_DISTANCIA_VERTICAL, SGC_BITACORA_BIT_ID)
VALUES
	(0, 0, 0, 0, 3),
	(0, 1, 0.0, 124/100, 3),
	(1, 2, 1.5, 54/100, 3),
	(2, 3, 1.5, 36/100, 3),
	(3, 4, 1.5, 35/100, 3),
	(4, 5, 1.5, 61/100, 3),
	(5, 6, 1.5, 76/100, 3)
  (6, 7, 1.5, 90/100, 3)
;
